[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "nlp-service"
version = "0.0.1"
dependencies = []
requires-python = ">= 3.10"

[tool.setuptools]
packages = ["app"]
